# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartRoom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartRoom
pod 'Alamofire'


  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  target 'SmartRoomTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SmartRoom-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SmartRoom-tvOS

  target 'SmartRoom-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
